# Generated by Django 4.2.3 on 2025-09-09 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('xp_next_level', models.IntegerField(default=1000)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_active', models.DateField(default=django.utils.timezone.now)),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='accounts.signup')),
            ],
        ),
    ]
