# Generated by Django 5.2.5 on 2025-09-10 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_video_description_video_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_videos', to='accounts.signup')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_by', to='accounts.video')),
            ],
            options={
                'unique_together': {('user', 'video')},
            },
        ),
    ]
